### PR TITLE
Simplify isForceArrayWithoutStdClass

### PR DESCRIPTION
**Pull request by herndlm**
Hi Tomas, It'd like to get your adaption merged in phpstan-src and while looking at it, instead of creating x comments, I thought to open up a PR instead :)

What do you think? Local CI is still green.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, I've checked briefly and it look good.
Let's trigger the CI :)

**Comment by herndlm** [comment]
fyi if you rebase on the latest phpstan branches, I'm also expecting some failing tests because of https://github.com/phpstan/phpstan-src/pull/1235
I tried to avoid triggering conflicts there, sorry if I still did

**Comment by TomasVotruba** [comment]
I see :)

The rebase give me some hard times... to be honest, if you can take over and finish it, it would be easier for me :pray: 
I barelly recall what I worked on 2 months ago :) the important is to deliver this to the core :+1:

**Comment by herndlm** [comment]
@TomasVotruba done. yeah that rebase hurt quite a bit. I ended up basically re-creating this branch, cherry-picking the commits on your already re-based branch and force-pushed, which worked nice :)
UPDATE: and in hindsight it makes sense for me now that the rebase on a rebased branch is not going to work nice. I could have simply dropped all previous commits too.

**Comment by TomasVotruba** [comment]
Thanks for this :+1: 

Do you think you can also propose the PR from your fork and takover completely? In case it's not much extra work for you.
If it helps, I can give you access to my fork.

**Comment by herndlm** [comment]
sure, will do that. If you're fine of giving me access, than that might be even simpler, so that we don't have to create a new PR in phpstan. But I can also create a new one, whatever you prefer :)

**Comment by TomasVotruba** [comment]
Here is invite: https://github.com/TomasVotruba/phpstan-src/invitations

But pick whatever is easier for you. If new PR is matter of 1 minute work, go for it :+1:

**Pull request merged**
